# Generated by Django 2.2.1 on 2019-05-06 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiply', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LearnMultiplyModel',
        ),
    ]
