# Generated by Django 2.2.1 on 2019-05-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multiply', '0002_delete_learnmultiplymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiplyUserRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('level', models.IntegerField(default=1)),
                ('experience', models.IntegerField(default=0)),
                ('next_level_experience', models.IntegerField(default=100)),
            ],
        ),
    ]
