# Generated by Django 2.2.1 on 2019-05-08 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiply', '0003_multiplyuserrank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiplyuserrank',
            old_name='next_level_experience',
            new_name='next_level_additional_experience',
        ),
    ]
