# Generated by Django 2.2.1 on 2019-05-08 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('multiply', '0004_auto_20190508_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplyuserrank',
            name='username',
        ),
        migrations.AddField(
            model_name='multiplyuserrank',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
