# Generated by Django 2.2.1 on 2019-05-08 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiply', '0005_auto_20190508_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiplyuserrank',
            old_name='next_level_additional_experience',
            new_name='next_level',
        ),
    ]
