# Generated by Django 2.2.1 on 2019-05-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiply', '0007_auto_20190508_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplyuserrank',
            name='experience_for_next_level',
            field=models.IntegerField(default=100),
        ),
    ]
