# Generated by Django 2.2.1 on 2019-05-08 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_loginformmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginFormModel',
        ),
    ]
